export const config = {
  SERVER_URL: process.env.NEXT_PUBLIC_SERVER_URL,
  SOCKET_URL: process.env.NEXT_PUBLIC_SOCKET_URL,
  FRONTEND_URL: process.env.NEXT_PUBLIC_FRONTEND_URL,
  STORAGE_URL: process.env.NEXT_PUBLIC_STORAGE_URL,
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  MIXPANEL_TOKEN: process.env.NEXT_PUBLIC_MIXPANEL_TOKEN,
};
